### ISSUE TITLE
Determine Technology Stack

### ISSUE THREAD

**Issue by dwitmerRX2** [RazorX2/anytime_draft#12]

**Comment by dwitmerRX2** [comment]
MEAN stack.

**Comment by frostme** [comment]
agreed with @dwitmerRX2 on mean stack.

| Development | Tech                                       |
| ------------- | ------------------------------- |
| Backend        | Nodejs + ExpressJS (sailsjs)      |
| Frontend       | AngularJS                                    |
| Database      | Mongo                                          |
| Mobile          | Ionic (angular + conversion)       |
